// Icônes pixel art 16x16 dessinées à la main (toute grille carrée est acceptée).
// Chaque caractère = 1 pixel ; "." = transparent.

const PAL = {
  k: "#1a1a1a", w: "#ffffff", g: "#c0c0c0", G: "#808080",
  y: "#f7d154", Y: "#d9a521", l: "#fff3a0",
  b: "#2a6bd1", B: "#173f8a", c: "#5bc0eb",
  r: "#e03c31", o: "#8b5a2b", O: "#c58a4a",
  n: "#3aa53a", N: "#1f6b1f", s: "#f2c9a0", p: "#9b59b6",
  f: "#fbb488", h: "#f6874f", e: "#ec6530", d: "#d6501f",
};

const ICONS = {
  folder: [
    "................",
    "................",
    ".kkkkk..........",
    "kllllyk.........",
    "kyyyyyykkkkkkkk.",
    "kyllllllllllllyk",
    "kylyyyyyyyyyyyYk",
    "kylyyyyyyyyyyyYk",
    "kylyyyyyyyyyyyYk",
    "kylyyyyyyyyyyyYk",
    "kylyyyyyyyyyyyYk",
    "kylyyyyyyyyyyyYk",
    "kyYYYYYYYYYYYYYk",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  briefcase: [
    "................",
    "................",
    "................",
    ".....kkkkkk.....",
    ".....k....k.....",
    ".kkkkkkkkkkkkkk.",
    ".kOOOOOOOOOOOOk.",
    ".kOOOOOOOOOOOOk.",
    ".kkkkkkllkkkkkk.",
    ".kOOOOOllOOOOOk.",
    ".kOOOOOOOOOOOOk.",
    ".kOOOOOOOOOOOOk.",
    ".kooooooooooook.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  cap: [
    "................",
    "................",
    ".......kk.......",
    ".....kkBBkk.....",
    "...kkBBBBBBkk...",
    ".kkBBBBBBBBBBkk.",
    "kBBBBBBBBBBBBBBk",
    ".kkBBBBBBBBBBkky",
    "...kkBBBBBBkk..y",
    "...kBkkkkkkBk..y",
    "...kBBBBBBBBk.yy",
    "...kBBBBBBBBk.yy",
    "....kkkkkkkk....",
    "................",
    "................",
    "................",
  ],
  gear: [
    "................",
    "......kkkk......",
    "..kk..kggk..kk..",
    "..kgkkkggkkkgk..",
    "...kggggggggk...",
    "..kggGkkkkGggk..",
    "kkkggk....kggkkk",
    "kgggk......kgggk",
    "kgggk......kgggk",
    "kkkggk....kggkkk",
    "..kggGkkkkGggk..",
    "...kggggggggk...",
    "..kgkkkggkkkgk..",
    "..kk..kggk..kk..",
    "......kkkk......",
    "................",
  ],
  trophy: [
    "................",
    "..kkkkkkkkkkkk..",
    "kkkyyyyyyyyyykkk",
    "k.kylyyyyyyyYk.k",
    "k.kylyyyyyyyYk.k",
    ".kkylyyyyyyyYkk.",
    "...kylyyyyyYk...",
    "....kyyyyyYk....",
    ".....kyyyYk.....",
    "......kyYk......",
    "......kyYk......",
    ".....kkyYkk.....",
    "....kYYYYYYk....",
    "....kOOOOOOk....",
    "....kkkkkkkk....",
    "................",
  ],
  gamepad: [
    "................",
    "................",
    "................",
    "................",
    "..kkkkk..kkkkk..",
    ".kgggggkkgggggk.",
    "kggkggggggggrggk",
    "kgkkkggggggrgbgk",
    "kggkggggggggbggk",
    "kggggggkkggggggk",
    "kgggggk..kgggggk",
    ".kgggk....kgggk.",
    "..kkk......kkk..",
    "................",
    "................",
    "................",
  ],
  mail: [
    "................",
    "................",
    "................",
    "kkkkkkkkkkkkkkkk",
    "kkwwwwwwwwwwwwkk",
    "kwkwwwwwwwwwwkwk",
    "kwwkwwwwwwwwkwwk",
    "kwwwkwwwwwwkwwwk",
    "kwwwwkwwwwkwwwwk",
    "kwwwwwkkkkwwwwwk",
    "kwwwwwwwwwwwwwwk",
    "kwwwwwwwwwwwwwwk",
    "kgggggggggggggGk",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  card: [
    "................",
    "................",
    "................",
    "kkkkkkkkkkkkkkkk",
    "kbbbbbbbbbbbbbbk",
    "kwwwwwwwwwwwwwwk",
    "kwkkkkwwwwwwwwwk",
    "kwksskwGGGGGGGwk",
    "kwksskwwwwwwwwwk",
    "kwkbbkwGGGGGwwwk",
    "kwkkkkwwwwwwwwwk",
    "kwwwwwwGGGGGGGwk",
    "kwwwwwwwwwwwwwwk",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  doc: [
    "..kkkkkkkkk.....",
    "..kwwwwwwwkk....",
    "..kwwwwwwwkgk...",
    "..kwwwwwwwkkkk..",
    "..kwwwwwwwwwwk..",
    "..kwGGGGGGGGwk..",
    "..kwwwwwwwwwwk..",
    "..kwGGGGGGGGwk..",
    "..kwwwwwwwwwwk..",
    "..kwGGGGGGwwwk..",
    "..kwwwwwwwwwwk..",
    "..kwGGGGGGGGwk..",
    "..kwwwwwwwwwwk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  computer: [
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kggggggggggggk.",
    ".kgkkkkkkkkkkgk.",
    ".kgkcccccccckgk.",
    ".kgkcbcccccckgk.",
    ".kgkcccccccckgk.",
    ".kgkcccccccckgk.",
    ".kgkkkkkkkkkkgk.",
    ".kggggggggggnGk.",
    ".kkkkkkkkkkkkkk.",
    "......kggk......",
    "....kkggggkk....",
    "...kggggggggk...",
    "...kkkkkkkkkk...",
    "................",
  ],
  error: [
    "................",
    ".....kkkkkk.....",
    "...kkrrrrrrkk...",
    "..krrrrrrrrrrk..",
    ".krrwwrrrrwwrrk.",
    ".krrwwwrrwwwrrk.",
    "krrrrwwwwwwrrrrk",
    "krrrrrwwwwrrrrrk",
    "krrrrrwwwwrrrrrk",
    "krrrrwwwwwwrrrrk",
    ".krrwwwrrwwwrrk.",
    ".krrwwrrrrwwrrk.",
    "..krrrrrrrrrrk..",
    "...kkrrrrrrkk...",
    ".....kkkkkk.....",
    "................",
  ],
  avatar: [
    "................",
    "....kkkkkkkk....",
    "...kooooooook...",
    "..kooooooooook..",
    "..koossssssook..",
    "..kossssssssok..",
    "..ksskksskkssk..",
    "..kssssssssssk..",
    "..kssrssssrssk..",
    "..ksssrrrrsssk..",
    "...kssssssssk...",
    "....kkkkkkkk....",
    "...kbbbbbbbbk...",
    "..kbbbbbbbbbbk..",
    ".kbbbbbbbbbbbbk.",
    ".kkkkkkkkkkkkkk.",
  ],
  // bouton « Quitter » : tuile orange façon XP en 24×24 (plus fine que les icônes 16×16)
  power: [
    "........................",
    "...wwwwwwwwwwwwwwwwww...",
    "..wffffffffffffffffffw..",
    ".wffffffffffffffffffffw.",
    ".wffffffffffffffffffffw.",
    ".wfffffffffwwfffffffffw.",
    ".wfffffffffwwfffffffffw.",
    ".whhhhhwwhhwwhhwwhhhhhw.",
    ".whhhhwwwhhwwhhwwwhhhhw.",
    ".whhhhwwhhhwwhhhwwhhhhw.",
    ".whhhwwwhhhwwhhhwwwhhhw.",
    ".whhhwwhhhhwwhhhhwwhhhw.",
    ".weeewweeeewweeeewweeew.",
    ".weeewweeeeeeeeeewweeew.",
    ".weeewwweeeeeeeewwweeew.",
    ".weeeewweeeeeeeewweeeew.",
    ".weeeewwweeeeeewwweeeew.",
    ".wdddddwwwwwwwwwwdddddw.",
    ".wdddddddwwwwwwdddddddw.",
    ".wddddddddddddddddddddw.",
    ".wddddddddddddddddddddw.",
    "..wddddddddddddddddddw..",
    "...wwwwwwwwwwwwwwwwww...",
    "........................",
  ],
  sound: [
    "................",
    "................",
    "................",
    "......k.........",
    ".....kk...k.....",
    "kkkkkgk....k....",
    "kgggggk.k...k...",
    "kgggggk..k..k...",
    "kgggggk..k..k...",
    "kgggggk.k...k...",
    "kkkkkgk....k....",
    ".....kk...k.....",
    "......k.........",
    "................",
    "................",
    "................",
  ],
  mute: [
    "................",
    "................",
    "................",
    "......k.........",
    ".....kk.........",
    "kkkkkgk.........",
    "kgggggk.r...r...",
    "kgggggk..r.r....",
    "kgggggk...r.....",
    "kgggggk..r.r....",
    "kkkkkgk.r...r...",
    ".....kk.........",
    "......k.........",
    "................",
    "................",
    "................",
  ],
};

// Variantes colorées du document
const tint = (key) => ICONS.doc.map((row, i) => (i === 5 || i === 7 ? row.replace(/G/g, key) : row));
ICONS.docBlue = tint("b");
ICONS.docGreen = tint("n");
ICONS.docRed = tint("r");
ICONS.docPurple = tint("p");

const cache = {};
export function iconURL(name) {
  if (cache[name]) return cache[name];
  const grid = ICONS[name] || ICONS.doc;
  const c = document.createElement("canvas");
  c.width = c.height = grid.length;
  const ctx = c.getContext("2d");
  grid.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === "." || !PAL[ch]) return;
      ctx.fillStyle = PAL[ch];
      ctx.fillRect(x, y, 1, 1);
    });
  });
  return (cache[name] = c.toDataURL());
}

export function iconImg(name, size = 32) {
  const img = new Image(size, size);
  img.src = iconURL(name);
  img.className = "px";
  img.alt = "";
  img.draggable = false;
  return img;
}
